version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: mssql-container
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_PID: "Developer"  # 可选值: Developer, Express, Standard, Enterprise
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
